name: Orca Demo - Image Scan 2

on:
  schedule:
    # run 2 times a day
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:

  lint-check:
    name: lint-check
    # we had issues with ubuntu, currently using MacOS
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: echo "Your linting goes here..."

  unit-tests:
    name: unit-tests
    runs-on: ubuntu-latest
    steps:
    - run: echo "Your Unit tests go here..."

  format-check:
    name: format-check
    runs-on: ubuntu-latest
    steps:
    - name: format-check
      run: echo "Your format checking goes here..."

  build-and-scan-image:
    name: build-and-scan-image
    needs: [lint-check,unit-tests,format-check]
    runs-on: ubuntu-latest
    env: 
      IMAGE_NAME: ghcr.io/orcasecurity/base_infra:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Container Image
      run: docker build -t ${IMAGE_NAME} .

    - name: Orca Container image Security Scan
      uses: orcasecurity/shiftleft-container-image-action@v1
      with:
          api_token: ${{ secrets.ORCA_TOKEN_DEMO_ACCOUNT }}
          project_key: "shiftleft-security-awesome_repo"
          image: ${{ env.IMAGE_NAME}}
          console_output: "table"
          format: "table"
    - name: Check disk space
      run: |
          echo "Free space:"
          df -h
  push-to-registry:
    name: push-to-registry
    needs: [build-and-scan-image]
    runs-on: ubuntu-latest
    steps:
    - run: echo "Pushing image to docker registry"
